<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Marketing\Enums;

class PromotionTypeEnum
{
    const C_CODED_COUPON = 'CODED_COUPON';
    const C_MARKDOWN_SALE = 'MARKDOWN_SALE';
    const C_ORDER_DISCOUNT = 'ORDER_DISCOUNT';
    const C_VOLUME_DISCOUNT = 'VOLUME_DISCOUNT';
}
