<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Fulfillment\Enums;

class ReasonForRefundEnum
{
    const C_BUYER_CANCEL = 'BUYER_CANCEL';
    const C_SELLER_CANCEL = 'SELLER_CANCEL';
    const C_ITEM_NOT_RECEIVED = 'ITEM_NOT_RECEIVED';
    const C_BUYER_RETURN = 'BUYER_RETURN';
    const C_ITEM_NOT_AS_DESCRIBED = 'ITEM_NOT_AS_DESCRIBED';
    const C_OTHER_ADJUSTMENT = 'OTHER_ADJUSTMENT';
    const C_SHIPPING_DISCOUNT = 'SHIPPING_DISCOUNT';
}
